on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Render docs

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Turn on auto-dark mode
        shell: bash
        run: |
          awk 'NR==1, /---/ {if (!done && /---/) {print "---\nfilters:\n  - auto-dark"; done=1; next}} 1' README.qmd > index.qmd
          quarto add gadenbuie/quarto-auto-dark --no-prompt

      - name: Render README
        shell: bash
        run: quarto render index.qmd --to html

      # From GitHub's "Static HTML" workflow template
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
